# Generated by Django 5.2.6 on 2025-11-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="productCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="عنوان"
                    ),
                ),
                (
                    "url_title",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="عنوان در url"
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField()),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categorys",
            },
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("price", models.IntegerField()),
                (
                    "short_description",
                    models.CharField(db_index=True, max_length=500, null=True),
                ),
                ("description", models.TextField(db_index=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField()),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", max_length=200, unique=True
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, null=True, to="product.productcategory"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="productTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tag", models.CharField(db_index=True, max_length=300)),
                (
                    "product_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
