# Generated by Django 5.2.6 on 2025-11-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productbrand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/product"),
        ),
    ]
