# Generated by Django 5.2.6 on 2025-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productbrand",
            name="url_title",
            field=models.CharField(db_index=True, default=2, max_length=300),
            preserve_default=False,
        ),
    ]
