# Generated by Django 5.2.6 on 2025-11-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=300)),
                ("full_name", models.CharField(max_length=300)),
                ("message", models.TextField()),
                ("response", models.TextField(blank=True, null=True)),
                ("is_read_by_admin", models.BooleanField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "contact us",
                "verbose_name_plural": "contact us list",
            },
        ),
    ]
