# Generated by Django 5.2.6 on 2025-11-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="is_read_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
