# Generated by Django 5.2.6 on 2025-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0002_alter_contactus_is_read_by_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="profilemodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="images")),
            ],
        ),
    ]
